# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from src.client import nexus_bus_pb2 as nexus__bus__pb2


class NexusBusStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Read = channel.unary_unary(
        '/nexusbus.NexusBus/Read',
        request_serializer=nexus__bus__pb2.ReadRequest.SerializeToString,
        response_deserializer=nexus__bus__pb2.ReadResponse.FromString,
        )
    self.Write = channel.unary_unary(
        '/nexusbus.NexusBus/Write',
        request_serializer=nexus__bus__pb2.WriteRequest.SerializeToString,
        response_deserializer=nexus__bus__pb2.WriteResponse.FromString,
        )
    self.HealthCheck = channel.unary_unary(
        '/nexusbus.NexusBus/HealthCheck',
        request_serializer=nexus__bus__pb2.HealthRequest.SerializeToString,
        response_deserializer=nexus__bus__pb2.HealthResponse.FromString,
        )


class NexusBusServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Read(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Write(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HealthCheck(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NexusBusServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Read': grpc.unary_unary_rpc_method_handler(
          servicer.Read,
          request_deserializer=nexus__bus__pb2.ReadRequest.FromString,
          response_serializer=nexus__bus__pb2.ReadResponse.SerializeToString,
      ),
      'Write': grpc.unary_unary_rpc_method_handler(
          servicer.Write,
          request_deserializer=nexus__bus__pb2.WriteRequest.FromString,
          response_serializer=nexus__bus__pb2.WriteResponse.SerializeToString,
      ),
      'HealthCheck': grpc.unary_unary_rpc_method_handler(
          servicer.HealthCheck,
          request_deserializer=nexus__bus__pb2.HealthRequest.FromString,
          response_serializer=nexus__bus__pb2.HealthResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'nexusbus.NexusBus', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
